services:
  pydocass-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: pydocass_dev
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEBIUS_API_KEY=${NEBIUS_API_KEY}
    command: npm run dev
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true 