# Use the official Node.js image as the base image
FROM node:20-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install the dependencies with all dev dependencies
RUN npm install

# Expose the port the app will run on
EXPOSE 3000

# Start the application in development mode with hot reloading
CMD ["npm", "run", "dev"] 